### ISSUE TITLE
Different transition times for each step

### ISSUE THREAD

**Issue by sk58** [impress/impress.js#339] opened 2013-10-16 17:57 UTC
I'm using this code to automate between steps...
```
$(document).ready(function() {
                $(document).on('impress:stepenter', function(e) {
                    var currentSlide = $(e.target).attr('id');
 
                    if (currentSlide === 'work') {
                        setTimeout(api.next, 0);
						  
                    } else if (currentSlide === 'work-zoom') {
                        window.location = 'work-zoom';
						
                    }
                });
            });
// ]]></script>
```
What could I add to effect the transition time between 2 particular slides.

Also I want to control whether non active steps are visible or not on certain steps.

This has failed to work:
```
#slide .step:not(.active) {
    opacity: 1;
}
```
Thanks for any ideas...

**Comment by FagnerMartinsBrack** [comment] 2016-03-19 05:36
Closing as a duplicate of #142.

**Closed** 2016-03-19 05:36 UTC
