### ISSUE TITLE
Feature Request: NPM

### ISSUE THREAD

**Issue by brodavi** [impress/impress.js#426] opened 2014-09-18 19:13 UTC
Hi! I would really love it if I could npm install impress.js (and use it via browserify).

https://gist.github.com/coolaj86/1318304

Thanks! :D  I love impress.js!

**Comment by FagnerMartinsBrack** [comment] 2016-04-14 11:19
Closing as a duplicate of https://github.com/impress/impress.js/issues/512. When that issue is closed we will have NPM support :).

**Closed by FagnerMartinsBrack** 2016-04-14 11:19 UTC
