### ISSUE TITLE
SVG animation support in Impress.js

### ISSUE THREAD

**Issue by geek1011** [impress/impress.js#533] opened 2016-03-16 13:46 UTC
I have some code in my Impress.js presentation which I have added to enable support for SVG animation using [Vivus](https://github.com/maxwellito/vivus). How could this be integrated with Impress.js?
````html
<script src="vivus.js"></script>
````

````javascript
var els = document.getElementsByTagName("svg");
    for (var ii = 0; ii < els.length; ii++) {
        if (els[ii].classList.contains("animated") || els[ii].getAttribute("data-animate") == "true"){
            els[ii].style.visibility = "hidden";
        }
    }
    
    var onStepEnter = function(event) {
	    var toAnimate = curEl.getElementsByTagName("svg");
	    for (var i = 0; i < toAnimate.length; i++) {
	        if (toAnimate[i].classList.contains("animated") || toAnimate[i].getAttribute("data-animate") == "true"){
	            toAnimate[i].style.visibility = "visible";
	              new Vivus(toAnimate[i], {duration: toAnimate[i].getAttribute("data-animation-speed") || 200}, function(){});
	        }
	    }    
    }
````

Two examples:

````html
<svg data-animate="true">
(svg code here)
</svg>
<svg data-animate="true" data-animation-speed="400">
(other svg code here)
</svg>
````

**Comment by FagnerMartinsBrack** [comment] 2016-03-16 22:08
Probably a duplicate of https://github.com/impress/impress.js/issues/501 and https://github.com/impress/impress.js/pull/143. Can you check if this request is duplicate, and if not can you explain what is the problem instead of jumping into the solution?

A library should not create custom code for specific libraries, but solve problems that are blocking for those integrations to be done properly.

**Comment by geek1011** [comment] 2016-03-16 23:07
The problem is that I do not know how I can turn this into a library. This is not a duplicate of #501 , but it is quite similar to #143

**Comment by FagnerMartinsBrack** [comment] 2016-03-17 00:47
> The problem is that I do not know how I can turn this into a library

Sorry I didn't suggested you should turn this into a library. I was talking about creating custom code in impress.js tied to specific libraries. Maybe we could create something that helps fixing your use case in a more broad sense so that it can be useful for similar use cases?

In order to do that we need to understand details of what is the problem that you are not being able to achieve with impress.js, the more concrete and focused details the better.

**Comment by FagnerMartinsBrack** [comment] 2016-04-14 11:33
Closing due to the lack of feedback from [the OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). If you want to work in the PR again, feel free to comment here to open up the discussion again

**Comment by FagnerMartinsBrack** [comment] 2016-04-14 11:34
We will continue to track this on #143.

**Closed by FagnerMartinsBrack** 2016-04-14 11:33 UTC
