### ISSUE TITLE
Nested steps?

### ISSUE THREAD

**Issue by abbr** [impress/impress.js#507] opened 2015-12-29 02:20 UTC
Hi, is it feasible to implement nested `class="step"` elements to create zoom-in effect without duplication? I think this would be a cool enhancement.

**Comment by peternerlich** [comment] 2016-01-10 21:15
Do you mean the white background with *duplication*? That's defined for the `slide` class. If I get you right, you can simply do an empty step in the right position of the previous one.

**Comment by peternerlich** [comment] 2016-01-10 21:43
I just discovered that this is already being discussed in #81.

**Comment by FagnerMartinsBrack** [comment] 2016-04-14 11:37
Closing as a duplicate of #81.

**Closed by FagnerMartinsBrack** 2016-04-14 11:37 UTC
