### ISSUE TITLE
How can I interact with the elements of another div besides #impress?

### ISSUE THREAD

**Issue by renzomontejo** [impress/impress.js#254] opened 2013-01-20 11:58 UTC
For example:

       <div id="impress">
		<div class="step" data-x="0" data-y="0" data-z="0">
			Test
		</div>
		<div class="step" data-x="0" data-y="0" data-z="-1000">
			Test
		</div>
	</div>
	<script type="text/javascript" src="<?php echo base_url();?>js/impress.js"></script>
	<script>impress().init();</script>
	
	<div class="logindiv">
		<form id="loginform">
			<label for="username">Username</label>
			<input type="text" id="username" name="username" /><br/>
			<label for="password">Password</label>
			<input type="password" id="password" name="password" /><br/>
			<a href="#">Go</a>
		</form>
	</div>

I can't click on the textboxes or the Go hyperlink inside the logindiv.. it seems like the mouse event listener is bound to impress.

How can I have a workaround on this? Thank you very much.

**Comment by FagnerMartinsBrack** [comment] 2016-02-09 10:03
Closing as a duplicate of #140

**Closed by FagnerMartinsBrack** 2016-02-09 10:03 UTC
