### ISSUE TITLE
Scaling problems with iframe in Safari

### ISSUE THREAD

**Issue by eisenheim94** [impress/impress.js#718] opened 2019-01-24 10:10 UTC
Hi! I have created flowchart with impress.js. I have 1st step as overview of all steps. If I open .html file it is working good, but when I'm including it with iframe on another page - it is not working proper in Safari. But if you will zoom out page (by using `Ctrl/Cmd -`) it will work. Also if you will click on this white area - it will zoom to other slides.
https://ukrenergo.maketry.xyz/kliyentam/dostup-do-merezh/

Normal view (not zoomed page):
![Normal page](https://i.imgur.com/pXKPU5K.png)

Zoomed out view (zoomed out twice with `Cmd -`):
![Zoomed out page](https://i.imgur.com/XNWHGNl.png)

I've noticed, that when I'm playing with iframe height (make it smaller) - it works.
E.g. when I set `height: 400px;` instead of `1750px` required to see whole flow.
And if you will click on other invisible (due to this bug) steps it will change iframe height to `400px` (I did it with JS) .
![iframe with 400px height](https://i.imgur.com/3yjwBeQ.png)

The same problem on iOS Safari (white screen).

**Comment by eisenheim94** [comment] 2019-01-24 13:39
P.S. I think, that it is thinking that steps are not in viewport and not drawing them

**Comment by eisenheim94** [comment] 2019-01-24 13:46
Also I can provide source code (html, css, js)

**Comment by simplePCBuilding** [comment] 2023-10-21 10:18
This I think has been resolved with some updates to Safari, but can you verify please? This might have even been caused by some APIs that were unsupported/broken at that time

**Comment by henrikingo** [comment] 2023-12-15 22:39
How would I verify it? It worked fine for me all the time :-)

**Closed by henrikingo** 2023-12-15 22:39 UTC
