### ISSUE TITLE
On Firefox, Impress.js animation effects doesn't look good

### ISSUE THREAD

**Issue by sam2tokyo** [impress/impress.js#743] opened 2019-09-20 03:15 UTC
Firefox's new browser is gaining a lot of popularity, but impress.js doesn't seem to work very well on it.  Animation effects such as zooming and moving to another slide creates a lot of jaggy and blurred effects that I didn't see while using Chrome or Brave.  

This seems to affect impress.js the most, however reveal/bespoken work just fine.  I actually developed a GUI editor to create impress.js presentation but I may have to change to a different one which is a bummer because I do like impress.js.

**Comment by henrikingo** [comment] 2019-09-22 15:45
Yes. I have filed #650 to track this issue and all it really does is to link to [an issue I filed in FF bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1424506).

If you want to help you could add more comments at the FF issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1424506

After some initial activity, it doesn't seem like they are really working on it.

**Comment by henrikingo** [comment] 2019-09-22 15:46
I will close this as duplicate of #650

**Closed by henrikingo** 2019-09-22 15:46 UTC
