### ISSUE TITLE
impress.js awesome in Chrome, terrible in Firefox 66.0.5

### ISSUE THREAD

**Issue by stratus-ss** [impress/impress.js#735] opened 2019-05-21 16:08 UTC
Problem statement: When a deck is more than 15 slides, transitions in Firefox are unbearably slow or stutter. Work fine in Chrome and Vivaldi.

Expanded information: 
32G Ram
Arch Linux
Core I7 4770
SSDs

I have this in the head

```
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=1024">
        <meta name="author" content="Steve Ovens">
        <!-- I am using the css available from the impress.js github-->
        <link href="css/impress-demo.css" rel="stylesheet">
        <link href="css/classic-slides.css" rel="stylesheet">
        <link href="css/mermaid.forest.css" rel="stylesheet">
        <link href="css/github.css" rel="stylesheet">

        <!-- These are my local css styles -->
        <link href="css/local_custom.css" rel="stylesheet">
        
    </head>
```

My local css:

```
/* These are my local CSS styles */

.topCentre {
    position: relative;
    top: -35px; 
    align-items: center; 
    text-align: center; 
    font-size: 2.05em
}

.whiteText{
    color: rgb(255, 255, 255);
}

.redText{
    color: red
}

.bulletFont{
    font-size: 32px
}

.commonBackgroundSettings{
    height: 700px; 
    width: 935px;
}

.redhatBackgroundSettings{
    background-image: url("../images/RedHat_background_scaled.png");
    height: 675px; 
    width: 905px;
}

.debianBackgroundSettings{
    background-image: url("../images/Debian_background.png"); 

}

.fedoraBackgroundSettings{
    background-image: url("../images/Fedora_background.png"); 
}

.archBackgroundSettings{
    background-image: url("../images/Arch_background.png"); 
}

.gentooBackgroundSettings{
    background-image: url("../images/Gentoo_background_1.png");
}

.fedoraHeadingSettings{
    position: relative;
    top: 15px; 
    align-items: center; 
    text-align: center; 
    font-size: 48pt 
}


.arrowRightIndentation {
    height: 40px; 
    width: 45px;
}

/* .textTransitions { width: 500px } */

/*
    ... so we define display to `inline-block` to enable transforms and
    transition duration to 0.5s ...
*/
.textTransitions {
    display: inline-block;
    -webkit-transition: 0.5s;
    -moz-transition:    0.5s;
    -ms-transition:     0.5s;
    -o-transition:      0.5s;
    transition:         0.5s;
}

/*
    ... and we want 'positioning` word to move up a bit when the step gets
    `present` class ...
*/
.textTransitions.present .positioning {
    -webkit-transform: translateY(-10px);
    -moz-transform:    translateY(-10px);
    -ms-transform:     translateY(-10px);
    -o-transform:      translateY(-10px);
    transform:         translateY(-10px);
}

/*
    ... 'rotating' to rotate a quarter of a second later ...
*/
.textTransitions.present .rotating {
    -webkit-transform: rotate(-10deg);
    -moz-transform:    rotate(-10deg);
    -ms-transform:     rotate(-10deg);
    -o-transform:      rotate(-10deg);
    transform:         rotate(-10deg);

    -webkit-transition-delay: 0.25s;
    -moz-transition-delay:    0.25s;
    -ms-transition-delay:     0.25s;
    -o-transition-delay:      0.25s;
    transition-delay:         0.25s;
}

/*
    ... and 'scaling' to scale down after another quarter of a second.
*/
.textTransitions.present .scalingUp {
    -webkit-transform: scale(5);
    -moz-transform:    scale(5);
    -ms-transform:     scale(5);
    -o-transform:      scale(5);
    transform:         scale(6);

    -webkit-transition-delay: 2.7s;
    -moz-transition-delay:    2.7s;
    -ms-transition-delay:     2.7s;
    -o-transition-delay:      2.7s;
    transition-delay:         2.7s;
}

.textTransitions.present .scalingDown {
    -webkit-transform: scale(0);
    -moz-transform:    scale(0);
    -ms-transform:     scale(0);
    -o-transform:      scale(0);
    -o-transform:      scale(0);
    transform:         scale(0);

    -webkit-transition-delay: 2.7s;
    -moz-transition-delay:    2.7s;
    -ms-transition-delay:     2.7s;
    -o-transition-delay:      2.7s;
    transition-delay:         2.7s;
}
```

When I move from the overview to the next slide stutters like crazy in firefox. Here are the first two

```
            <div id="overview" class="step" data-x="8000" data-y="3000" data-z="6000" data-scale="10"></div>

            <!-- Self Bio-->
            <div id="who" class="redhatBackgroundSettings step slide" data-x="0" data-y="0" data-z="0">
                <div class="topCentre whiteText">Who Is This Guy?</div>
                <p style="text-align: left;" >
                    <br>
                    <img src="images/Steve_and_Chewie.jpg" style="float: left;">&nbsp; &nbsp; &nbsp; &nbsp;
                    <span class="whiteText">Twitter -removed</span><br>
                </p>
                <div class="whiteText" style="text-align: center">removed</div>
            </div>
```

This is not the only place where there are big performance issues.

I am not sure that this is an impress.js, I don't know enough about FF under pinnings and javascript. I have 110 slides in the deck

**Comment by henrikingo** [comment] 2019-05-22 08:53
It seems the new Firefox Quantum versions often struggle with our advanced use of CSS3. #650 is another example.

I will leave this open for tracking and informational purposes, but it's really a FF problem, so nothing we can fix on impress.js side. (Note: That impress.js never targeted wide browser compatibility anyway. For example, some 3D slide shows never worked well on IE. The goal for impress.js is just to target the CSS standard, and hope that it works well on at least 1 browser.)

**Comment by stratus-ss** [comment] 2019-05-22 11:31
Thanks for the reply. I figured it was a browser issue. I just wanted to confirm

**Comment by henrikingo** [comment] 2019-05-22 12:03
If you ever observer FF becoming better, please report back here.

**Comment by henrikingo** [comment] 2019-09-22 15:49
I will close this as a duplicate of #650

**Closed by henrikingo** 2019-09-22 15:49 UTC
