### ISSUE TITLE
Contact form with impress.js

### ISSUE THREAD

**Issue by marlenetiare** [impress/impress.js#514] opened 2016-02-09 00:39 UTC
Hi!

I've a contact form inside the sections on my website. I'm using impress.js but I can't write a message in my contact form because when i push the space bar, changes the section to the next section in the website.

Can I eliminate the function "the space bar" in this part of the website?
when my user is typing your message to me.
Thanks a lot!

**Comment by bartaz** [comment] 2016-02-09 08:11
Hi,

You are right, impress.js right now 'assumes' it's a presentation, so space key is detected as an action to move to next slide. You may also have same problems with arrow keys if user want's to move cursor in input field.

I see two options how you can fix that.

1. If it's a website it's possible that you don't need keyboard to change the 'slides' at all, on any section. If that's correct you can remove this part from impress.js code for yourself. You can safely remove this part: https://github.com/impress/impress.js/blob/master/js/impress.js#L689-L728

2. If on other hand you would like to keep keyboard navigation (space bar, arrows) on the other sections of the page and only disable it for you contact form, you would need to add a piece of script to your page.

Assuming that your contact form has an id of `contact` like that:
```
<div id="contact" class="step">
    your contact form here
</div>
```
Use such script somewhere on the page (for example after initializing impress.js):

```javascript
<script>
impress().init();

document.getElementById('contact').addEventListener('keyup', function(event) {
    event.preventDefault();
});
</script>
```

This [event.preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) causes keyboard `keyup` event to stop in contact section, so impress.js doesn't receive it and will not move to next slide.

I hope it helps. If anything doesn't work as expected let us know, we will try to figure it out.

**Comment by FagnerMartinsBrack** [comment] 2016-02-09 10:05
Hi @marlenetiare thanks for opening the issue! As the comment above, we don't have this feature on impress yet but we have open issues such as #140 to track that.

Closing, since this is a duplicate of #140.

**Closed by FagnerMartinsBrack** 2016-02-09 10:05 UTC

**Comment by marlenetiare** [comment] 2016-02-10 01:59
thanks alot for the quickly!
finally, the javascript doesn't work for me, but in the file impress.js I erased a couple lines and it worked perfectly.

```
        document.addEventListener("keydown", function ( event ) {
            if ( (event.keyCode >= 37 && event.keyCode <= 40) ) {
                event.preventDefault();
            }
        }, false);

        document.addEventListener("keyup", function ( event ) {
            if ( (event.keyCode >= 37 && event.keyCode <= 40) ) {
                switch( event.keyCode ) {
                    case 33: // pg up
                    case 37: // left
                    case 38: // up
                             api.prev();
                             break;
                    //case 9:  // tab
                    //case 32: // space 
                    case 34: // pg down
                    case 39: // right
                    case 40: // down
                             api.next();
                             break;
                }

                event.preventDefault();
            }
        }, false);
```
thank u so much again!

**Comment by FagnerMartinsBrack** [comment] 2016-02-10 02:46
When you remove this code you remove the key handlers that make the presentation work using only the keys (left, right, etc.). If you don't use the keys that way and use only the  programmatic API, then this is indeed a good approach to solve the problem :+1:

**Comment by 3ruce** [comment] 2016-07-22 10:07
Likewise, the javascript option doesn't work for me so I'm going with editing lines 730 - 739 to comment out the tab key... That said, it would be great if it was possible to return full control of the keyboard once the form fields are active/being edited...
