### ISSUE TITLE
bower install 0.5.3, different bower.json?

### ISSUE THREAD

**Issue by dizzyone** [impress/impress.js#471] opened 2015-04-14 12:07 UTC
Hey, I was debugging a friend's project and for some reason when downloading impress.js#0.5.3 through bower, it doesn't seem to get the right bower.json file. The bower.json lacks a main property, where the latest version (0.5.3) does have it in the bower.json. 

any ideas what could be going wrong? I fixed it by specifically installing bower with the latest commit SHA:

bower install 'git@github.com:bartaz/impress.js.git#efc184947a9b58ca30ad391146700513fd23a30c'

**Comment by bartaz** [comment] 2015-04-14 12:17
I wasn't the one adding bower support and `bower.json` file.
It may be connected to the fact that version 0.5.3 (as released on GitHub with repo tag https://github.com/bartaz/impress.js/tree/0.5.3) doesn't have bower file at all, it was added later on.

**Comment by dizzyone** [comment] 2015-04-14 12:20
That makes sense, thanks for responding.

In any case, if anyone else has this issue, the easiest way is to simply install the master branch like so:
bower install impress.js#master

**Comment by FagnerMartinsBrack** [comment] 2016-03-19 06:03
This issue will be closed once the version `0.6.0` is released.

**Comment by FagnerMartinsBrack** [comment] 2016-04-14 11:28
Closing as a duplicate of #512 (see bullet points).

**Closed by FagnerMartinsBrack** 2016-04-14 11:28 UTC
