### ISSUE TITLE
Strategies for an cube map (skymap)

### ISSUE THREAD

**Issue by oravecz** [impress/impress.js#145] opened 2012-04-30 18:31 UTC
I would like to "wrap" my #impress in a large cube to simulate a sky map. Is there any way to include an object in the #impress block that is not part of slide transitions? Kinda like a fixed global object, but one which will respond to transforms?

**Comment by bartaz** [comment] 2015-06-26 19:05
Duplicate of #8

**Closed by bartaz** 2015-06-26 19:05 UTC
