### ISSUE TITLE
Android Mobile Support

### ISSUE THREAD

**Issue by fioghual** [impress/impress.js#273] opened 2013-03-26 14:34 UTC
In Android ICS 4.0 with Chrome installed, impress.js works fine when "Request Desktop Site" is selected in the menu.

**Comment by deepu105** [comment] 2016-03-14 05:12
yes may be an option to enable for mobile would be good so that it can be programatically done

**Comment by FagnerMartinsBrack** [comment] 2016-03-19 05:57
Closing as duplicate of #282.

**Closed by FagnerMartinsBrack** 2016-03-19 05:57 UTC
